version: '3.9'

services:
  database:
    restart: always
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - ./.database.env
    volumes:
      - ./database/var/lib/postgresql:/var/lib/postgresql
  server:
    restart: always
    build: './server'
    volumes:
      - /app/node_modules
    environment:
      - PORT=80
